controller_manager:
  ros__parameters:
    update_rate: 500

    car_controller:
      type: car_controller/CarController

car_controller:
  ros__parameters:
    use_sim_time: false
    imu_topic: /imu/data
    torque_limit: 20.0
