controller_manager:
  ros__parameters:
    update_rate: 500

    lqr_controller:
      type: lqr_controller/LQRController

lqr_controller:
  ros__parameters:
    use_sim_time: false
    imu_topic: /imu/data
    torque_limit: 20.0
