controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    car_controller:
      type: car_controller/CarController

car_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_front_hip_joint
      - left_rear_hip_joint
      - left_wheel_joint
      - right_front_hip_joint
      - right_rear_hip_joint
      - right_wheel_joint
    imu_sensor_name: imu
    torque_limit: 20.0
    state_topic: robot_state
    target_topic: robot_target
    cmd_vel_topic: cmd_vel
