controller_manager:
  ros__parameters:
    update_rate: 500

    mujoco_sim_controller:
      type: lqr_controller/MujocoSimController

    lqr_controller:
      type: lqr_controller/LQRController

mujoco_sim_controller:
  ros__parameters:
    use_sim_time: true
    effort_limit: 20.0

lqr_controller:
  ros__parameters:
    use_sim_time: true
    imu_topic: /imu_imu_sensor/imu
    torque_limit: 20.0
    default_kp:
      - 30.0  # left_front_hip_joint
      - 30.0  # left_rear_hip_joint
      - 0.0   # left_wheel_joint
      - 30.0  # right_front_hip_joint
      - 30.0  # right_rear_hip_joint
      - 0.0   # right_wheel_joint
    default_kd:
      - 2.0   # left_front_hip_joint
      - 2.0   # left_rear_hip_joint
      - 0.01   # left_wheel_joint
      - 2.0   # right_front_hip_joint
      - 2.0   # right_rear_hip_joint
      - 0.01   # right_wheel_joint
